name: Build APK

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-apk.yml'
      - 'app/**' # مسیر پروژه Android
      - 'build.gradle'
      - 'settings.gradle'
  pull_request:
    paths:
      - '.github/workflows/build-apk.yml'
      - 'app/**'
      - 'build.gradle'
      - 'settings.gradle'
  workflow_dispatch:

env:
  SAMPLE_PATH: app # مسیر پروژه Android
  compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
  compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
  compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # 1. Checkout کد
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. فعال‌سازی Gradle Build Cache
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 3. ایجاد فایل local.properties
      - name: Create local.properties
        run: |
          echo "sdk.dir=/usr/lib/android-sdk" > local.properties
        working-directory: ${{ github.workspace }}

      # 4. Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # 5. Install Gradle Wrapper
      - name: Install Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew --version

      # 6. Build Debug APK با refresh dependencies
      - name: Build Debug APK
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ../gradlew assembleDebug --stacktrace --info --refresh-dependencies

      # 7. Upload APK as Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ env.SAMPLE_PATH }}/build/outputs/apk/debug/app-debug.apk
